name: Auto deploy
on:
  workflow_run:
    workflows: ["Build image"]
    types:
      - completed

env:
  RELEASE: numperson-tencent

jobs:
  deploy:
    runs-on: jet
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Metadata
        id: meta
        uses: docker/metadata-action@master
        with:
          images: |
            ghcr.io/byzanteam/${{ env.RELEASE }}
          tags: |
            type=sha

      - name: deploy production tower admin
        uses: byzanteam/jet-actions/deploy-application-charts@main
        with:
          values_file: "./.deploy/values.local.yaml"
          image_tag: ${{ steps.meta.outputs.version }}
          private_key: ${{ secrets.DEPLOYMENT_RUNNER_PRIVATE_KEY }}
          namespace: production
          release_name: production

