name: auto deploy
on:
  workflow_dispatch:
    inputs:
      image-tag:
        description: 'The image tag deployed to the production environment'
        default: 'latest'
        type: string
        required: true
      release-selection:
        description: 'Version selection'
        default: 'company.yaml'
        type: choice
        options:
          - company
          - yls
        required: true
jobs:
  deploy:
    runs-on: jet
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: deploy prview numperson tencent
        uses: byzanteam/jet-actions/deploy-application-charts@main
        with:
          values_file: "./.deploy/${{ inputs.release-selection }}.yaml"
          image_tag: ${{ inputs.image-tag }}
          private_key: ${{ secrets.DEPLOYMENT_RUNNER_PRIVATE_KEY }}
          namespace: production
          release_name: ${{ inputs.release-selection }}