name: Build image

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: image-builder
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Build and push
        uses: byzanteam/jet-actions/fe-build-image@main
        with:
          registries: |-
            ${{ secrets.ALIYUN_SKYLARK_REGISTRY }}
            ghcr.io,byzanteam,${{ github.repository_owner }},${{ github.token }}
          cache_type: registry
          dockerfile: ./Dockerfile

